# APPLICATION
spring:
  application:
    name: authentication
  output:
    ansi:
      enabled: ALWAYS

  # DATABASE
  datasource:
    url: jdbc:postgresql://localhost:5432/authentication
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        type: trace
    open-in-view: false
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6378

# SERVER
server:
  port: 8082

# LOGGING
logging:
  level:
    root: WARN
  include-application-name: false
  pattern:
    console: "\u001b[38;5;0m%d{hh:mm:ss} \u001b[31;1m%level \u001b[33m%file::%L %n \u001b[38;5;0m --- \u001b[35m %m \u001b[0m %n"

# SECURITY
ACCESS_SECRET: MY_SECRET_ACC
